services:
  web:
    build: .
    image: api:1.0
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  db:
    image: mysql:8.4
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - '3307:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysqldata:
    driver: local
